version: '3'

x-constants:
  LUMOS_SOURCE_DIR: &LUMOS_SOURCE_DIR /lumos_source

services:
  lumos-builder-base:
    build:
      context: .
      dockerfile: build.Dockerfile
    volumes:
      - type: bind
        source: .
        target: *LUMOS_SOURCE_DIR
        bind:
          create_host_path: true
    working_dir: *LUMOS_SOURCE_DIR # Not necessary, but for clarity
    command:  ["tail", "-f", "/dev/null"]

  lumos-builder-build:
    extends: lumos-builder-base
    command: bash -c "bin/clean.sh && bin/iso.sh"